mqtt:
  broker:
    port: 8883
    #websocket_port: 8080
    host: 0.0.0.0
    jmx: false
  consumer:
    host: vm://localhost
    subscriptions: owntracks.user.*
    timeout: 5000
    session-window-seconds: 300

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

server:
  port: 8080

---
spring:
    profiles: aws

server:
  port: 80